src/Entity/Customers.php
<?php

namespace App\Entity;

use App\Repository\CustomersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CustomersRepository::class)
 */
class Customers extends Users
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champs est recquis")
     * @Assert\Regex(
     *     "/\D/",
     *     message="Seule les lettres sont acceptées")
     * @Assert\Length(
     *     charset="UTF-8",
     *     max="255",
     *     maxMessage="255 caractères maximum.")
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champs est recquis")
     * @Assert\Regex(
     *     "/\D/",
     *     message="Seule les lettres sont acceptées")
     * @Assert\Length(
     *     charset="UTF-8",
     *     max="255",
     *     maxMessage="255 caractères maximum.")
     */
    private $lastname;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank(message="Ce champs est recquis")
     * @Assert\Type("\DateTimeInterface")
     */
    private $birthdate;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champs est recquis")
     * @Assert\Length(
     *     charset="UTF-8",
     *     max="255",
     *     maxMessage="255 caractères maximum.")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champs est recquis")
     * @Assert\Length(
     *     charset="UTF-8",
     *     max="255",
     *     maxMessage="255 caractères maximum.")
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champs est recquis")
     * @Assert\Regex(
     *     "/\D/",
     *     message="Seule les lettres sont acceptées")
     * @Assert\Length(
     *     charset="UTF-8",
     *     max="255",
     *     maxMessage="255 caractères maximum.")
     */
    private $city;

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname() :?string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(?\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Entity/Reservations.php
<?php

namespace App\Entity;

use App\Repository\ReservationsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ReservationsRepository::class)
 */
class Reservations
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank(message="Ce champs est recquis")

     */
    private $User;

    /**
     * @ORM\OneToOne(targetEntity=Books::class, inversedBy="reservation")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank(message="Ce champs est recquis")
     */
    private $book;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="Ce champs est recquis")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $endDate;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ce champs est recquis")
     */
    private $status;

    public function __toString():string
    {
        return $this->id;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Users
    {
        return $this->User;
    }

    public function setUser(?Users $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getBook(): ?Books
    {
        return $this->book;
    }

    public function setBook(Books $book): self
    {
        $this->book = $book;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Controller/ReservationsController.php
<?php

namespace App\Controller;

use App\Entity\Reservations;
use App\Repository\BooksRepository;
use App\Repository\ReservationsRepository;
use App\Service\ReservationService;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;


/**
 * @Route("/reservations")
 */
class ReservationsController extends AbstractController
{
    /**
     * Allow a user to reserve a book
     *
     * @IsGranted("ROLE_CUSTOMER"),
     * @Route("/reserve/{bookId}", name="book_reservation", methods={"GET","POST"}),
     */
    public function new(BooksRepository $booksRepository,
                        int $bookId,
                        ReservationService $reservationService): Response
    {
        $duration = '+3 day';
        $status = 'reserved';
        $reservationService->makeOrEditReservation($booksRepository, $bookId, $duration, $status);

        return $this->redirectToRoute('catalog');
    }

    /**
     * Confirm the loan of a book
     *
     * @IsGranted("ROLE_EMPLOYEE"),
     * @param BooksRepository $booksRepository
     * @param int $bookId
     * @return Response
     * @Route("/edit/{bookId}", name="book_loaning", methods={"GET","POST"})
     */
    public function setLoaning(BooksRepository $booksRepository,
                               int $bookId,
                               ReservationService $reservationService): Response
    {
        $duration = '+21 day';
        $status = 'borrowed';
        $reservationService->makeOrEditReservation($booksRepository, $bookId, $duration, $status);

        return $this->redirectToRoute('catalog');
    }

    /**
     * display the all the reservations
     *
     * @IsGranted("ROLE_EMPLOYEE"),
     * @Route("/show_loanings", name="loanings_show", methods={"GET","POST"})
     */
    public function showLoaning(ReservationsRepository $reservationsRepository,
                                ReservationService $reservationService): Response
    {
        $reservations = $reservationService->getAllReservations($reservationsRepository);

        return $this->render('/reservations/showAll.html.twig', $reservations);
    }

    /**
     * display the reservations of one user
     *
     * @IsGranted("ROLE_CUSTOMER"),
     * @Route("/show_user_loanings", name="loanings_user_show", methods={"GET","POST"})
     */
    public function showUserLoaning(ReservationService $reservationService): Response
    {
        $userReservations = $reservationService->getUserReservations();

        return $this->render('/reservations/showUserReservations.html.twig', $userReservations);
    }

        /**
         * Delete a book's reservation (the user returned the book to the library)
         *
         * @Route("/delete/{reservationId}", name="delete_reservation", methods={"GET","POST"})
         */
        public function delete(ReservationsRepository $reservationsRepository,
                               int $reservationId,
                               ReservationService $reservationService): Response
        {
            $reservationService->deleteReservation($reservationsRepository, $reservationId);

            return $this->redirectToRoute('loanings_show');
        }
}

templates/reservations/_display_late_loan.html.twig
<div class="card mb-3 col-md-12 col-lg-6 p-0">
    <div class="row g-0">
        <div class="col-sm-2 col-xl-3">
            <img src="{{ asset('uploads/booksCover/' ~ userLateBook.image) }}"
                 class="img-fluid rounded-start w-100"
                 alt="image de couverture du livre">
        </div>
        <div class="col-sm-10 col-xl-9">
            {% if userLateBook.reservation %}

                    <div class="card_header color_borrowed" class="card-header rounded-0 text-light d-flex justify-content-between">
                        <p class="m-0 p-0">Emprunté</p>
                        <p class="m-0 p-0">A rendre pour le : {{ userLateBook.reservation.endDate|format_datetime('short', 'none', locale='fr') }}</p>
                    </div>
                {% endif %}

            <div class="container">
                <div class="card-body row">

                    <div class="col-12">
                        <h5 class="card-title title">{{ userLateBook.title }}</h5>
                        <p class="card-text m-0 p-0">
                            <small>
                                {{ userLateBook.literaryGenre }} |
                                {{ userLateBook.releaseDate|format_datetime('short', 'none', locale='fr') }} |
                                {{ userLateBook.author }}
                            </small>
                        </p>
                        <p class="card-text m-0 p-0">{{ userLateBook.description }}</p>
                        {% if is_granted("ROLE_EMPLOYEE") %}
                            <p>Emprunté par : {{ userLateBook.reservation.user.fullname }} </p>
                        {% endif %}
                    </div>

                    <div class="col-12 text-end mt-2">
                        {% if userLateBook.reservation %}
                            <p class="text-danger">EN RETARD</p>
                            {% if is_granted('ROLE_EMPLOYEE') %}
                                <a class="btn btn-success text-light" href="{{ path('delete_reservation', { 'reservationId': userLateBook.reservation.id }) }}">Confirmer le retour</a>
                            {% endif%}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/reservations/_display_late_reservations.html.twig
<div class="card mb-3 col-md-12 col-lg-6 p-0">
    <div class="row g-0">
        <div class="col-sm-2 col-xl-3">
            <img src="{{ asset('uploads/booksCover/' ~ userLateReservation.image) }}"
                 class="img-fluid rounded-start w-100"
                 alt="image de couverture du livre">
        </div>
        <div class="col-sm-10 col-xl-9">
            <div class="card_header color_reserved" class="card-header rounded-0 text-light d-flex justify-content-between">
                <p class="m-0 p-0">Réservé</p>
                <p class="m-0 p-0">Retour prévu le : {{ userLateReservation.reservation.endDate|format_datetime('short', 'none', locale='fr') }}</p>
            </div>
            <div class="container">
                <div class="card-body row">

                    <div class="col-8">
                        <h5 class="card-title title">{{ userLateReservation.title }}</h5>
                        <p class="card-text m-0 p-0">
                            <small>
                                {{ userLateReservation.literaryGenre }} |
                                {{ userLateReservation.releaseDate|format_datetime('short', 'none', locale='fr') }} |
                                {{ userLateReservation.author }}
                            </small>
                        </p>
                        <p class="card-text m-0 p-0">{{ userLateReservation.description }}</p>
                    </div>

                    <div class="col-4">
                        {% if userLateReservation.reservation %}
                            <p class="card-text text-danger">Votre réservation a expiré</p>
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

templates/reservations/_display_loan.html.twig
<div class="card mb-3 col-md-12 col-lg-6 p-0">
    <div class="row g-0">
        <div class="col-sm-2 col-xl-3">
            <img src="{{ asset('uploads/booksCover/' ~ userBook.image) }}"
                 class="img-fluid rounded-start w-100"
                 alt="image de couverture du livre">
        </div>
        <div class="col-sm-10 col-xl-9">
            {% if userBook.reservation %}

                {% if userBook.reservation.status == 'reserved' %}
                        <div class="card_header color_reserved" class="card-header rounded-0 text-light d-flex justify-content-between">
                            <p class="m-0 p-0">Réservé</p>
                            <p class="m-0 p-0">Retour prévu le : {{ userBook.reservation.endDate|format_datetime('short', 'none', locale='fr') }}</p>
                        </div>
                {% else %}

                    <div class="card_header color_borrowed" class="card-header rounded-0 text-light d-flex justify-content-between">
                        <p class="m-0 p-0">Emprunté</p>
                        <p class="m-0 p-0">Retour prévu le : {{ userBook.reservation.endDate|format_datetime('short', 'none', locale='fr') }}</p>
                    </div>
                {% endif %}
            {% endif %}

            <div class="container">
                <div class="card-body row">

                    <div class="col-12">
                        <h5 class="card-title title">{{ userBook.title }}</h5>
                        <p class="card-text m-0 p-0">
                            <small>
                                {{ userBook.literaryGenre }} |
                                {{ userBook.releaseDate|format_datetime('short', 'none', locale='fr') }} |
                                {{ userBook.author }}
                            </small>
                        </p>
                        <p class="card-text m-0 p-0">{{ userBook.description }}</p>
                    </div>

                    <div class="col-12 text-end mt-2">
                        {% if is_granted('ROLE_EMPLOYEE') %}
                            <a class="btn btn-success text-light"
                               href="{{ path('delete_reservation', { 'reservationId': userBook.reservation.id }) }}">
                                Confirmer le retour</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/reservations/showAll.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des emprunts{% endblock %}
{% block description %} Médiathèque Chapelle Curreaux : voir les emprunts et réservations {% endblock %}


{% block main %}
<h1 class="text-center mb-4 title">Liste des emprunts</h1>
<div class="w-100 d-flex flex-wrap justify-content-between">
    {% if lateBooks is empty and books is empty %}
        <p>Aucun emprunt en cours.</p>
    {% endif %}

    {% if lateBooks %}
        {% for userLateBook in lateBooks %}
            {% include('reservations/_display_late_loan.html.twig') %}
        {% endfor %}
    {% endif %}

    {% if books %}
        {% for userBook in books %}
            {% include('reservations/_display_loan.html.twig') %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/reservations/showUserReservations.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes emprunts et réservations{% endblock %}
{% block description %} Médiathèque Chapelle Curreaux : voir mes emprunts et réservations {% endblock %}

{% block main %}
<h1 class="text-center mb-4 title">Mes emprunts et Réservations</h1>
<div class="w-100 d-flex flex-wrap justify-content-between">
    {% if userLateBooks or userBooks or userLateReservations %}
        {% for userLateBook in userLateBooks %}
            {{ include('reservations/_display_late_loan.html.twig') }}
        {% endfor %}
        
        {% for userLateReservation in userLateReservations %}
            {{ include('reservations/_display_late_reservations.html.twig') }}
        {% endfor %}
        
        {% for userBook in userBooks %}
            {{ include('reservations/_display_loan.html.twig') }}
        {% endfor %}
    {% else %}
        <p>Vous n'avez pas de réservation ou de livre emprunté en cours.</p>
    {% endif %}
</div>
{% endblock %}